title: RSSFlow Reader
description: A powerful RSS reader extension for Chrome
theme: minima
baseurl: "/RSSFlow-doc"  # 替换成你的仓库名

# 多语言支持
languages:
  - en
  - zh

# 导航配置
header_pages:
  - index.md
  - privacy/en.md
  - privacy/zh.md 
