title: RSSFlow Reader
description: Your Smart RSS Reading Experience.
theme: minima
baseurl: "/RSSFlow-doc"  # 确保与你的GitHub仓库名完全一致
url: "https://oinzen.github.io"  # 替换为你的GitHub Pages URL

# 多语言支持
languages:
  - en
  - zh

# 导航配置
header_pages:
  - index.md
  - privacy/en.md
  - privacy/zh.md 
