title: RSSFlow Reader
description: Your Smart RSS Reading Experience.
baseurl: "/RSSFlow-doc"
url: "https://oinzen.github.io"

# 使用 minima 主题
theme: minima
markdown: kramdown

# 启用必要的插件
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-feed

# 确保资源文件被包含
sass:
  sass_dir: _sass
  style: compressed

# 多语言支持
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "en"
    values:
      lang: en
  - scope:
      path: "zh"
    values:
      lang: zh

include:
  - _pages
  - .htaccess

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
