title: RSSFlow Reader
description: Your Smart RSS Reading Experience.
theme: minima
baseurl: "/RSSFlow-doc"
url: "https://oinzen.github.io"

# 多语言支持
languages:
  - en
  - zh

# 导航配置
header_pages:
  - index.html
  - en/index.html
  - zh/index.html
  - privacy/en.md
  - privacy/zh.md

# 默认语言
default_lang: en

# 语言显示名称
lang_names:
  en: English
  zh: 中文
