source "https://rubygems.org"

gem "jekyll", "~> 4.3.3"
gem "minima"
gem "webrick", "~> 1.8"
gem "jekyll-redirect-from"
gem "jekyll-seo-tag"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end 